//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloSpinner
{
	
	
	public partial class Resource
	{
		
		public partial class array
		{
			
			// aapt resource value: 0x7f050000
			public const int planets_array = 2131034112;
			
			private array()
			{
			}
		}
		
		public partial class attr
		{
			
			private attr()
			{
			}
		}
		
		public partial class drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private drawable()
			{
			}
		}
		
		public partial class id
		{
			
			// aapt resource value: 0x7f060000
			public const int spinner = 2131099648;
			
			private id()
			{
			}
		}
		
		public partial class layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private layout()
			{
			}
		}
		
		public partial class @string
		{
			
			// aapt resource value: 0x7f040000
			public const int planet_prompt = 2130968576;
			
			private @string()
			{
			}
		}
	}
}
