// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HelloL10N
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int flag = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int flag_button = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int dialog_text = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int dialog_title = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int text_a = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text_b = 2130968578;
			
			private String()
			{
			}
		}
	}
}
